// <auto-generated />
using System;
using CMDB.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMDB.Infrastructure.Migrations
{
    [DbContext(typeof(CMDBContext))]
    [Migration("20220104102927_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMDB.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AccID")
                        .HasName("PK_Account")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("ApplicationId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TypeID")
                        .HasName("PK_AccountType")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("AccountType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Admin_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AdminId")
                        .HasName("PK_Admin")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("AccountId");

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Application", b =>
                {
                    b.Property<int>("AppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AppID")
                        .HasName("PK_Application")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_AssetCagegory")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("category");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TypeID")
                        .HasName("PK_AssetType")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("CategoryId");

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("AssetType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Configuration", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubCode")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CFN_Date")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("CFN_Number")
                        .HasColumnType("int");

                    b.Property<string>("CFN_Tekst")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Code", "SubCode");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Desktop", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("MAC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AssetTag")
                        .HasName("PK_Desktop_Asset");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Desktop");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Docking", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AssetTag")
                        .HasName("PK_Docking_Asset");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Docking");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.IdenAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ID")
                        .HasName("PK_IdenAccount")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("AccountId", "IdentityId", "ValidFrom", "ValidUntil")
                        .IsUnique()
                        .HasFilter("[IdentityId] IS NOT NULL");

                    b.ToTable("IdenAccount");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Identity", b =>
                {
                    b.Property<int>("IdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdenId")
                        .HasName("PK_Identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.IdentityType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TypeID")
                        .HasName("PK_IdentityType")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("IdentityType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Kensington", b =>
                {
                    b.Property<int>("KeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfKeys")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("DesktopAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DockingAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasLock")
                        .HasColumnType("bit");

                    b.Property<string>("LaptopAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("ScreenAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("KeyID")
                        .HasName("PK_Kensington")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("CategoryId");

                    b.HasIndex("DesktopAssetTag");

                    b.HasIndex("DockingAssetTag");

                    b.HasIndex("LaptopAssetTag");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("ScreenAssetTag");

                    b.HasIndex("TypeId");

                    b.ToTable("Kensington");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModfiedAdminAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Code")
                        .HasName("PK_Language");

                    b.HasIndex("LastModfiedAdminAdminId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Laptop", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("MAC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AssetTag")
                        .HasName("PK_Laptop_Asset");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DesktopAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DockingAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("IdentityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("KensingtonId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LaptopAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("MobileId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ScreenAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SubscriptionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SubsriptionId")
                        .HasColumnType("int");

                    b.Property<string>("TokenAssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Log");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("DesktopAssetTag");

                    b.HasIndex("DockingAssetTag");

                    b.HasIndex("IdentityId");

                    b.HasIndex("IdentityTypeId");

                    b.HasIndex("KensingtonId");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LaptopAssetTag");

                    b.HasIndex("MenuId");

                    b.HasIndex("MobileId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleTypeId");

                    b.HasIndex("ScreenAssetTag");

                    b.HasIndex("SubscriptionTypeId");

                    b.HasIndex("SubsriptionId");

                    b.HasIndex("TokenAssetTag");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("varchar(255)");

                    b.HasKey("MenuId")
                        .HasName("PK_Menu")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("ParentId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Mobile", b =>
                {
                    b.Property<int>("IMEI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IMEI")
                        .HasName("PK_Mobile");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Rights")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_PPermission");

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RAM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.ToTable("RAM");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("RoleId")
                        .HasName("PK_Role")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RolePerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RolePerm")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("MenuId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePerm");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RoleType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TypeId")
                        .HasName("PK_RoleType")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("RoleType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Screen", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AssetTag")
                        .HasName("PK_Screen_Asset");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Screen");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetCategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("MobileId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubsctiptionTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_Subscription");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("MobileId");

                    b.HasIndex("SubsctiptionTypeId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssetCategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_SubscriptionType");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("LastModifiedAdminId");

                    b.ToTable("SubscriptionType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Token", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Deactivate_reason");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAdminId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AssetTag")
                        .HasName("PK_Token_Asset");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("LastModifiedAdminId");

                    b.HasIndex("TypeId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Account", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Application", "Application")
                        .WithMany("Accounts")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK_Account_Application")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Accounts")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Account_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AccountType", "Type")
                        .WithMany("Accounts")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Account_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AccountType", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("AccountTypes")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_AccountType_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Admin", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Account", "Account")
                        .WithMany("Admins")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Admin_Account")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Admins")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Admin_LastModiefiedAdmin")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Application", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Applications")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Application_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetCategory", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("AssetCategories")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_AssetCategory_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetType", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Types")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("AssetTypes")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_AssetType_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Desktop", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Desktops")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Desktop_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Desktops")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Desktop_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Desktops")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Desktop_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Desktops")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Desktop_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Docking", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Dockings")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Docking_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Dockings")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Docking_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Dockings")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Docking_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Dockings")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Docking_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.IdenAccount", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Account", "Account")
                        .WithMany("Identities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Accounts")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModifiedAdmin")
                        .WithMany("IdenAccounts")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_IdenAccount_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Identity");

                    b.Navigation("LastModifiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Identity", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Language", "Language")
                        .WithMany("Identities")
                        .HasForeignKey("LanguageCode")
                        .HasConstraintName("FK_Identity_Language")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Identities")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Identity_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.IdentityType", "Type")
                        .WithMany("Identities")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Identity_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.IdentityType", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("IdentityTypes")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_IdentityType_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Kensington", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Kensingtons")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Kensington_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Desktop", "Desktop")
                        .WithMany("Keys")
                        .HasForeignKey("DesktopAssetTag")
                        .HasConstraintName("FK_Key_Deskop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Docking", "Docking")
                        .WithMany("Keys")
                        .HasForeignKey("DockingAssetTag")
                        .HasConstraintName("FK_Key_Docking")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Laptop", "Laptop")
                        .WithMany("Keys")
                        .HasForeignKey("LaptopAssetTag")
                        .HasConstraintName("FK_Key_Laptop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Kensingtons")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Kensington_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Screen", "Screen")
                        .WithMany("Keys")
                        .HasForeignKey("ScreenAssetTag")
                        .HasConstraintName("FK_Key_Screen")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Kensingtons")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Kensington_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Desktop");

                    b.Navigation("Docking");

                    b.Navigation("Laptop");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Screen");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Language", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany()
                        .HasForeignKey("LastModfiedAdminAdminId");

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Laptop", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Laptops")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Laptop_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Laptops")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Laptop_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Laptops")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Laptop_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Laptops")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Laptop_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Log", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Account", "Account")
                        .WithMany("Logs")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Log_Account")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AccountType", "AccountType")
                        .WithMany("Logs")
                        .HasForeignKey("AccountTypeId")
                        .HasConstraintName("FK_Log_AccounType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "Admin")
                        .WithMany("Logs")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_Log_Admin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Application", "Application")
                        .WithMany("Logs")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK_Log_Application")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Logs")
                        .HasForeignKey("AssetCategoryId")
                        .HasConstraintName("FK_Log_Category")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Logs")
                        .HasForeignKey("AssetTypeId")
                        .HasConstraintName("FK_Log_AssetType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Desktop", "Desktop")
                        .WithMany("Logs")
                        .HasForeignKey("DesktopAssetTag")
                        .HasConstraintName("FK_Log_Desktop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Docking", "Docking")
                        .WithMany("Logs")
                        .HasForeignKey("DockingAssetTag")
                        .HasConstraintName("FK_Log_Docking")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Logs")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Log_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.IdentityType", "IdentityType")
                        .WithMany("Logs")
                        .HasForeignKey("IdentityTypeId")
                        .HasConstraintName("FK_Log_IdentityType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Kensington", "Kensington")
                        .WithMany("Logs")
                        .HasForeignKey("KensingtonId")
                        .HasConstraintName("FK_Log_KensingTone")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Language", null)
                        .WithMany("Logs")
                        .HasForeignKey("LanguageCode");

                    b.HasOne("CMDB.Domain.Entities.Laptop", "Laptop")
                        .WithMany("Logs")
                        .HasForeignKey("LaptopAssetTag")
                        .HasConstraintName("FK_Log_Laptop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Menu", "Menu")
                        .WithMany("Logs")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK_Log_Menu")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Mobile", "Mobile")
                        .WithMany("Logs")
                        .HasForeignKey("MobileId")
                        .HasConstraintName("FK_Log_Mobile")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Permission", "Permission")
                        .WithMany("Logs")
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK_Log_Permission")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Role", "Role")
                        .WithMany("Logs")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Log_Role")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.RoleType", "RoleType")
                        .WithMany("Logs")
                        .HasForeignKey("RoleTypeId")
                        .HasConstraintName("FK_Log_RoleType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Screen", "Screen")
                        .WithMany("Logs")
                        .HasForeignKey("ScreenAssetTag")
                        .HasConstraintName("FK_Log_Screen")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("Logs")
                        .HasForeignKey("SubscriptionTypeId")
                        .HasConstraintName("FK_Log_SubscriptionType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Logs")
                        .HasForeignKey("SubsriptionId")
                        .HasConstraintName("FK_Log_Subscription")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Token", "Token")
                        .WithMany("Logs")
                        .HasForeignKey("TokenAssetTag")
                        .HasConstraintName("FK_Log_Token")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("AccountType");

                    b.Navigation("Admin");

                    b.Navigation("Application");

                    b.Navigation("AssetType");

                    b.Navigation("Category");

                    b.Navigation("Desktop");

                    b.Navigation("Docking");

                    b.Navigation("Identity");

                    b.Navigation("IdentityType");

                    b.Navigation("Kensington");

                    b.Navigation("Laptop");

                    b.Navigation("Menu");

                    b.Navigation("Mobile");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("RoleType");

                    b.Navigation("Screen");

                    b.Navigation("Subscription");

                    b.Navigation("SubscriptionType");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Menu", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Menu_Menu")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Mobile", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Mobiles")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Mobile_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Mobiles")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Mobile_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Mobiles")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Mobile_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "MobileType")
                        .WithMany("Mobiles")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Mobile_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("MobileType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Permission", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModifiedAdmin")
                        .WithMany("Permissions")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Permission_CreatedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModifiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Role", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Roles")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Role_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.RoleType", "Type")
                        .WithMany("Roles")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Role_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RolePerm", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModifiedAdmin")
                        .WithMany("RolePerms")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_RolePerm_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Menu", "Menu")
                        .WithMany("Permissions")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK_RolePerm_Menu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK_RolePerm_Permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastModifiedAdmin");

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RoleType", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("RoleTypes")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_RoleType_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Screen", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Screens")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Screen_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Screens")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Screen_Identity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Screens")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Screen_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Screens")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Screen_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AssetCategoryId")
                        .HasConstraintName("FK_Subscription_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Subscription_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Subscriptions")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Subscription_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Mobile", "Mobile")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MobileId")
                        .HasConstraintName("FK_Subscription_Mobile")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubsctiptionTypeId")
                        .HasConstraintName("FK_Subscription_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Mobile");

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.SubscriptionType", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("SubscriptionTypes")
                        .HasForeignKey("AssetCategoryId")
                        .HasConstraintName("FK_AssetType_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("SubscriptionTypes")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_SubscriptionType_LastModifiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("LastModfiedAdmin");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Token", b =>
                {
                    b.HasOne("CMDB.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Tokens")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Token_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMDB.Domain.Entities.Identity", "Identity")
                        .WithMany("Tokens")
                        .HasForeignKey("IdentityId")
                        .HasConstraintName("FK_Token_Identity")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.Admin", "LastModfiedAdmin")
                        .WithMany("Tokens")
                        .HasForeignKey("LastModifiedAdminId")
                        .HasConstraintName("FK_Token_LastModfiedAdmin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CMDB.Domain.Entities.AssetType", "Type")
                        .WithMany("Tokens")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Token_Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Identity");

                    b.Navigation("LastModfiedAdmin");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Account", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Identities");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Admin", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AccountTypes");

                    b.Navigation("Admins");

                    b.Navigation("Applications");

                    b.Navigation("AssetCategories");

                    b.Navigation("AssetTypes");

                    b.Navigation("Desktops");

                    b.Navigation("Dockings");

                    b.Navigation("IdenAccounts");

                    b.Navigation("Identities");

                    b.Navigation("IdentityTypes");

                    b.Navigation("Kensingtons");

                    b.Navigation("Laptops");

                    b.Navigation("Logs");

                    b.Navigation("Mobiles");

                    b.Navigation("Permissions");

                    b.Navigation("RolePerms");

                    b.Navigation("Roles");

                    b.Navigation("RoleTypes");

                    b.Navigation("Screens");

                    b.Navigation("Subscriptions");

                    b.Navigation("SubscriptionTypes");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Application", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("Desktops");

                    b.Navigation("Dockings");

                    b.Navigation("Kensingtons");

                    b.Navigation("Laptops");

                    b.Navigation("Logs");

                    b.Navigation("Mobiles");

                    b.Navigation("Screens");

                    b.Navigation("Subscriptions");

                    b.Navigation("SubscriptionTypes");

                    b.Navigation("Tokens");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Desktops");

                    b.Navigation("Dockings");

                    b.Navigation("Kensingtons");

                    b.Navigation("Laptops");

                    b.Navigation("Logs");

                    b.Navigation("Mobiles");

                    b.Navigation("Screens");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Desktop", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Docking", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Identity", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Desktops");

                    b.Navigation("Dockings");

                    b.Navigation("Laptops");

                    b.Navigation("Logs");

                    b.Navigation("Mobiles");

                    b.Navigation("Screens");

                    b.Navigation("Subscriptions");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.IdentityType", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Kensington", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Language", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Laptop", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Logs");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Mobile", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Role", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.RoleType", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Screen", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.SubscriptionType", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("CMDB.Domain.Entities.Token", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
